services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trainings
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/data/postgres

  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=password
    ports:
      - "6379:6379"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    networks:
      - default
    ports:
      - "8080:8080"

volumes:
  postgres-db:
